# Use an official Node.js 19.7.0 runtime as the base image
FROM node:19.7.0

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

# Install the serve package globally
RUN npm install -g serve

ENV VITE_APP_BACKEND_URL=https://4188-203-115-68-29.ngrok-free.app
# Expose the port that the app will run on
EXPOSE 5125

# Start the React app using serve, explicitly specifying the port
CMD ["serve", "-s", "dist", "-l", "5125"]